TeamSodam/sodam-server

.github/workflows/main_deploy.yml, src/routes/user/index.js
<br/>
- 음 나 로그인 api짰어! 
- resolved: #3 
<br/>
- 새로운 패키지 중에 xxx 설치했어 
<br/>
=> ➕ [ADD] : user폴더  index.js 추가  #3

package-lock.json, src/script/spreadsheet.js
<br/>
- spreadsheet DB 연동 문제 해결
<br/>
- spreadsheet.js 파일 수정 
<br/>
=> 🔨 [FIX] : DB 연동 오류 해결 #5

.gitignore, package-lock.json, package.json, src/db/index.js, src/db/spreadsheet.js, src/script/spreadsheet.js
<br/>
- 구글 스프레드시트와 데이터베이스 연결
- 데이터베이스 연동 
- 지금까지 스프레드시트 내용 저장 
- resolved: #5 
<br/>
- 관련 기능 주석 처리, 데이터베이스 오염 방지
- 실행시킬 때 nodemon으로 돌려야함
<br/>
=> Feature/spreadsheet #5

src/constants/responseMessage.js, src/db/shop.js, src/routes/shop/bookmarkGET.js, src/routes/shop/index.js, src/routes/shop/shopGET.js
<br/>
- [GET] /shop/bookmark?sort=?offset={}&limit={} api 제작 
- 추후 로그인 미들웨어 붙인 이후, 이미지 데이터 들어온 이후 검토 필요
- resolved: #16 
<br/>
<br/>
=> Feature/get bookmarked shop #16

src/constants/responseMessage.js, src/db/index.js, src/db/review.js, src/routes/index.js, src/routes/review/index.js, src/routes/review/reviewLikePOST.js
<br/>
- [POST] /review/:reviewId/like 완성
- 클라이언트에서 받은 isLiked의 값이 db에 저장된 값과 같을 때에는 변화가 일어나지 않도록 분기처리 함.
- review테이블의 like_count도 신경써서 제어함 (isLiked false이면 count깎고, true이면 count 올리기)
- resolved: #18 
<br/>
<br/>
=> ✨ [FEAT] : [POST] /review/:reviewId/like api 완성  #18

src/constants/responseMessage.js, src/db/index.js, src/db/review.js, src/routes/index.js, src/routes/review/index.js, src/routes/review/reviewShopIdSortPageGET.js
<br/>
- response message 작성
- db orm 작성
- 라우터 작성
- resolved: #12
<br/>
성공인데 응답 내용이 없는 경우 status 코드를 200을 보내고 빈 배열을 보내줍니다.
<br/>
=> Feature/get shop review #12

src/db/review.js, src/routes/review/index.js, src/routes/review/reviewLikePOST.js, src/routes/review/reviewScrapPOST.js
<br/>
- /review/:reviewId/scrap api 완성
- resolved: #22 (해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
<br/>
=> [FEATURE] [POST] /review/:reviewId/scrap api 완성 #22

src/constants/responseMessage.js, src/db/review.js, src/routes/shop/index.js, src/routes/shop/shopReviewIdGET.js
✨ [FEAT] : [GET] /shop/:shopId/review/:reviewId #25
<br/>
-  [GET] /shop/:shopId/review/:reviewId api 제작 
- resolved: #25 
<br/>
<br/>
=> ✨ [FEAT] : [GET] /shop/:shopId/review/:reviewId api제작 #25

package-lock.json, package.json, src/constants/responseMessage.js, src/db/user.js, src/lib/jwtHandlers.js, src/middlewares/auth.js, src/routes/auth/authLoginPOST.js, src/routes/auth/authSignupPOST.js, src/routes/auth/index.js, src/routes/index.js, src/routes/shop/bookmarkGET.js
<br/>
- /auth/signup 구현
- /auth/login 구현
- checkuser 미들웨어 구현
- 비밀번호를 암호화해서 db에 저장하는 로직, 리프레쉬토큰을 이용하는 로직은 추후 릴리즈 이후에 개발할 예정입니다
- resolved: #41 
<br/>
<br/>
- JWT 토큰 이용하기 위해서는 슬랙에 보내둔 키를 .env 파일에 추가해야 합니다. 
- 이 로그인 회원가입 pr이 디벨롭에 머지되면 checkuser 미들웨어 사용할 수 있어요.
- 사용방법은 일단 제가 유저 더미를 db에 넣어두면 그 중 하나의 email과 password를 postman으로 보내고, 리턴값으로 받은 accesstoken을 checkuser가 필요한 api의 request헤더에 넣으면 됩니다!
=> Feature/sign up, log in 회원가입, 로그인 구현

src/constants/responseMessage.js, src/db/shop.js, src/routes/shop/index.js, src/routes/shop/shopRecommendGET.js, src/sodam-server-authentication.json
<br/>
- 메인화면 뷰 소품샵 추천 기능 api 개발
- 타입별(랜덤별/북마크수별) 소품샵 추천 기능
- resolved: #23 
<br/>
- 이미지 데이터 삽입 이후 테스트 진행 필요(더미 데이터 없어서 아직 검사 못함)
<br/>
=> [FEATURE] [GET] /shop/recommend?type api 완성 #23

src/constants/responseMessage.js, src/db/shop.js, src/routes/shop/index.js, src/routes/shop/shopCategoryGET.js
<br/>
- 메인화면 뷰에서 필요한 카테고리별 랜덤 소품샵 추천 작업 완료
- 랜덤 접근 가능 or 더보기에서 카테고리 선택 기능 가능
- resolved: #29
<br/>
- 만약 한국어로 query가 들어오면, 주의 필요(띄어쓰기도 인식)
<br/>
=> [FEATURE] [GET] /shop/category?type api 완성 #29

src/constants/responseMessage.js, src/db/review.js, src/routes/review/index.js, src/routes/review/reviewRecentGET.js
<br/>
- 오늘 날짜에 작성된 리뷰 데이터를 제공
- 해당 뷰에 필요한 리뷰 데이터 모두 제공
- resolved: #33
<br/>
- 날짜가 우리나라 기준이 아님. 이는 개선이 필요할 듯.
<br/>
=> [FEATURE] [GET] /review/recent #33

src/constants/responseMessage.js, src/db/shop.js, src/routes/shop/index.js, src/routes/shop/shopSearchGET.js
<br/>
- 검색창에 입력한 쿼리값에 따라 소품샵 이름을 검색하고 해당 소품샵의 정보를 전달함
- resolved: #36
<br/>
- 중간중간 검색 결과가 달라질 때의 상황에도 맞는 코드 구현 필요함 
<br/>
=> [FEATURE] [GET] /shop/search?keyword #36

src/db/review.js, src/routes/my/index.js, src/routes/my/myReviewGET.js, src/routes/my/myScrapGET.js
<br/>
- 마이리뷰 부분에 checkuser 미들웨어를 추가
- resolved: #50
<br/>
<br/>
=> ➕ [ADD] : 마이리뷰에 checkuser 미들웨어 붙이기 #50

package-lock.json, package.json, src/middlewares/slackAPI.js, src/routes/auth/authLoginPOST.js, src/routes/auth/authSignupPOST.js, src/routes/my/myReviewGET.js, src/routes/my/myScrapGET.js, src/routes/review/reviewLikePOST.js, src/routes/review/reviewRecentGET.js, src/routes/review/reviewScrapPOST.js, src/routes/review/reviewShopIdSortPageGET.js, src/routes/shop/bookmarkGET.js, src/routes/shop/bookmarkPOST.js, src/routes/shop/shopCategoryGET.js, src/routes/shop/shopGET.js, src/routes/shop/shopRecommendGET.js, src/routes/shop/shopReviewIdGET.js, src/routes/shop/shopSearchGET.js, src/routes/shop/shopShopIdGET.js, src/routes/shop/shopShopIdLocationGET.js, src/routes/user/userGET.js
<br/>
- 슬랙 웹훅 설정 및 모든 API에 연동
- 에러 내용 보냄
- resolved: #49 (해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
<br/>
=> Feature/slack webhook #49

package-lock.json, package.json, src/db/spreadsheet.js, src/script/inserShop.js, src/script/insertReviewData.js, src/script/insertReviewImage.js, src/script/insertReviewItem.js, src/script/insertReviewTag.js, src/script/insertTag.js, src/script/insertUser.js
<br/>
- 스프레드 시트 연동해 db에 데이터 저장
-  user테이블
- tag 테이블 
- review 테이블
- review_tag 테이블
- review_item 테이블
- review_image 테이블
- resolved: #44 (해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
<br/>
=> ✨ [FEAT] : 유저, 리뷰 관련 더미데이터 스크립트 작성 #44

src/routes/review/reviewShopIdSortPageGET.js
<br/>
- 작성자 썸네일 데이터 형식 스트링에서 스트링 배열로 변경
- resolved: #56
<br/>
<br/>
=> 🔨 [FIX] : 작성자 썸네일 이미지 스트링 배열로 변경 #56

src/routes/review/reviewRecentGET.js
<br/>
- 유저 썸네일 이미지 배열로 변경 
<br/>
<br/>
=> 🔨 [FIX] : 유저 썸네일 이미지 배열로 고치기 #56

src/db/shop.js, src/routes/review/reviewShopIdSortPageGET.js
<br/>
-  writerThumnail 일반 string으로 고치기
- 리뷰가 없을 때 리뷰카운트 넣기
- resolved: #61 <br/>
<br/>
=> [BUG] shop review #61

src/constants/responseMessage.js, src/routes/my/myReviewGET.js
shopName, category 추가
responseMessage 추가
<br/>
- shopId, shopName, category 추가
- response 메시지 추가
- resolved: #64 
<br/>
돌아가게만 해뒀으니 코드 리팩터링 매우 필요
<br/>
=> [FIX] 내가 작성한 리뷰 response 수정

src/routes/review/reviewPOST.js
슬랙 웹훅 연결
DB에서 review_item unique key duplicate 문제 해결
<br/>
- 슬랙 웹훅 연결
- DB review_item id 설정값 늘려두기
- resolved: #68 
<br/>
<br/>
=> 🔨 [FIX] : 리뷰 작성 슬랙 웹훅 연결 및 오류 해결 #68

src/db/review.js, src/routes/shop/shopReviewIdGET.js
DB reivew.js getReviewByReviewId에서 select user_id 추가
created_at을 date로 받아와서 result에서 date:createdAt을 그냥 date로 변경
<br/>
- DB ORM 수정: review.js에서 getReviewByReviewId select에 user_id 추가
- orm에서 생성 날짜를 created_at에서 date로 바꿔서 불러오기 때문에 response data 만들 때 createdAt 미사용
- resolved: #70 
<br/>
review.js에서 getReviewByReviewId select에 user_id 추가
다른 로직에 영향 없는지 확인 필요함
<br/>
=> 🔨 [FIX] : 리뷰 상세 response 맞추기 #70

src/db/review.js, src/routes/my/myReviewGET.js
<br/>
- 리뷰아이디에 따라 가져와지는 것이 아니라 유저 아이디에 따라 리뷰가 불러와지도록 수정함
- 해당 리뷰에 맞게 이미지 붙이는 작업에서의 오류 해결
- resolved: #67
<br/>
<br/>
=> [FIX] : 내가 작성한 리뷰 불러올 때의 오류 해결 #67

src/routes/shop/index.js, src/routes/shop/shopReviewIdGET.js
좋아요, 스크랩 하면 isLiked, isScraped 불린값 변경됨
response 데이터에 date 넣음
<br/>
좋아요, 스크랩 하면 isLiked, isScraped 불린값 변경됨
response 데이터에 date 넣음
- resolved: #74  #75 
<br/>
<br/>
=> 🔨 [FIX] : 소품샵 상세페이지 좋아요, 스크랩, date 오류 고침 #74 #75

src/db/review.js, src/routes/my/myReviewGET.js, src/routes/my/myScrapGET.js, src/routes/review/reviewRecentGET.js, src/routes/review/reviewShopIdSortPageGET.js
<br/>
- 리뷰 작성, 리뷰 상세 수정
<br/>
<br/>
=> [MERGE] 수정 사항 반영

src/routes/shop/shopReviewIdGET.js
writer id를 좋아요 하는 유저의 id로 사용하고 있었음
<br/>
- 좋아요, 스크랩 다시 고침
- resolved: #75 
<br/>
<br/>
=> 🔨 [FIX] : 좋아요, 스크랩 고침 #75

src/db/review.js, src/routes/review/reviewShopIdSortPageGET.js
<br/>
- 최신 리뷰 불러오기에서 삭제한 리뷰도 불러오는 오류 수정
- 좋아요, 스크랩 안 되는 오류 수정
-
- resolved: #75 
<br/>
<br/>
=> [MERGE] 최신 리뷰, 좋아요, 스크랩 수정 사항 반영

src/constants/responseMessage.js, src/routes/review/reviewPOST.js
<br/>
- 리뷰 작성 시 request body 잘못 온 것 가드 
- resolved: #80 
<br/>
<br/>
=> 🔨 [FIX] : 리뷰 작성 잘못된 값 request 가드 #80

src/routes/shop/shopReviewIdGET.js
<br/>
- 리뷰 상세 response로 항상 같은 item 나오는 버그 수정
- resolved: #82 
<br/>
<br/>
=> 🔨 [FIX] : 리뷰 상세 response로 항상 같은 item 나오는 버그 수정 #82

src/db/review.js
<br/>
- 내가 작성한 리뷰 최신순으로 변경
<br/>
<br/>
=> [fix] 리뷰 최신순으로 뜨게 변경

__test__/shop.spec.js
<br/>
- 테스트 코드 작성
- resolved: #98 
<br/>
- 리팩터링은 할 게 없어서 안 함
<br/>
=> ⚡️ [TEST] : 소품샵 상세페이지 테스트 #98

__test__/shop.spec.js, src/constants/responseMessage.js, src/db/review.js, src/db/shop.js, src/lib/convertStringToNum.js, src/routes/admin/index.js, src/routes/admin/shopDataGET.js
<br/>
- 전체 소품샵 수
- 전체 리뷰 수
- 지역별 소품샵 수
- 테마별 소품샵 수
- 소품샵 종류별 소품샵 수
- 필요한 요소들 다 들어갔는지에 대한 테스트 코드 간단히 작성
- resolved: #123 
<br/>
<br/>
=> Feature/get shop data 

__test__/shop.spec.js, src/lib/util.js, src/routes/shop/shopReviewIdGET.js
<br/>
- [GET] /shop/:shopId/review/:reviewId 테스트 코드 작성
- 리턴 데이터에 필요한 값이 다 들어있는지  `expect(res.body.data).to.have.all.keys`를 통해 판별
- 리턴 데이터들의 타입이 명세서와 일치하는지 `expect().to.be.a('타입종류')` 를 통해 테스트
- message와 status가 맞는지 테스트
- `npx mocha __test__/shop.spec.js`를 통해 테스트 실행 가능
-  파라미터 잘못된 경우 리턴값 통일 
```
{
"status": 400,
"success": false,
"message": "파라미터 값이 잘못되었습니다"
}
```
- 파라미터에 알파벳 등의 문자가 들어온 경우 `'서버 내부 에러'`가 아니라  `'파라미터 값이 잘못되었습니다'` 메시지가 나오도록 에러 분기처리
- resolved: #88 
<br/>
<br/>
- utils 파일에 checkIsNum 함수를 추가했습니다. 쿼리나 파람으로 받은 값을 이곳에 넘기면 해당 값이 숫자인지 문자인지를 판별해서 숫자면 true, 문자이면 false를 리턴합니다. 에러처리를 세분화할 때 이용하면 좋을 것 같습니다 !
=> [Test] 리뷰 상세 정보 GET api 테스트 코드 작성, 리팩토링

__test__/shop.spec.js, src/lib/util.js, src/routes/shop/shopGET.js
<br/>
- [GET] /shop?area={}&sort={} 테스트 코드 작성
- 인기순 정렬일 때 
- mysave 정렬일 때 
- 로그인 안했을 때
- 로그인 했는데 저장된 소품샵이 없을 때
- 로그인 했는데 저장된 소품샵이 있을 때 
- [GET] /shop?theme={}&sort={}&offset={}&limit={} 테스트 코드 작성 
- 인기순 정렬일 때
- offset, limit 없을 때 `expect(res.body.data).to.have.lengthOf(20)`로 offset=1, limit=20 조건을 디폴트로 해서 총 20개가 들어오는 것을 확인 
- offset, limit 있을 때 : 배열 길이 점검
- 리뷰 많은 순 정렬일 때
- offset, limit 없을 때 `expect(res.body.data).to.have.lengthOf(20)`로 offset=1, limit=20 조건을 디폴트로 해서 총 20개가 들어오는 것을 확인 
- offset, limit 있을 때 : 배열 길이 점검
- `npx mocha __test__/shop.spec.js`를 통해 테스트 실행 가능
- resolved: #90 
<br/>
<br/>
=> [Test] 지역별, 테마별 소품샵 정보 불러오기 테스트코드 작성, 리팩토링 

__test__/review.spec.js, src/lib/util.js, src/routes/review/reviewLikePOST.js, src/routes/review/reviewScrapPOST.js
<br/>
- [POST] /shop/review/:reviewId/like 테스트 코드 작성
- reviewId가 이상한 값으로 오는 경우 파라미터가 잘못 되었다는 메시지 출력하도록 수정 (`util.checkIsNum` 이용)
- 정상적으로 요청 왔을 때 리뷰 좋아요, 리뷰 좋아요 취소 테스트
- 로그인 되어있지 않을 때 테스트
- 필요한 값이 없을 때 테스트
- 파라미터 값이 잘못되었을 때 테스트
- [POST] /shop/review/:reviewId/scrap 테스트 코드 작성
- reviewId가 이상한 값으로 오는 경우 파라미터가 잘못 되었다는 메시지 출력하도록 수정 (`util.checkIsNum` 이용)
- 정상적으로 요청 왔을 때 리뷰 스크랩, 리뷰 스크랩 취소 테스트
- 로그인 되어있지 않을 때 테스트
- 필요한 값이 없을 때 테스트
- 파라미터 값이 잘못되었을 때 테스트
- `npx mocha __test__/review.spec.js`를 통해 테스트 실행 가능
- resolved: #92
<br/>
<br/>
=> [Test] 리뷰 좋아요, 리뷰 스크랩 테스트 코드 작성, 리팩토링

__test__/shop.spec.js, src/db/shop.js, src/lib/util.js, src/routes/shop/bookmarkGET.js
<br/>
- [GET] /shop/bookmark?sort={}&offset={}&limit={} 테스트 코드 작성
- 저장 많은 순 정렬 : offset, limit 없을 때
- 리뷰 많은 순 정렬 : offset =1, limit=5일 때
- 최근 저장 순 정렬  : offset =2, limit=10일 때
- 저장한 소품샵이 없을 때 
- 쿼리값 아무것도 없을 때 : 디폴트 sort=save, offset=1, limit=20의 조건으로 나오는 지 테스트
- 로그인 안 되어 있을 때
- [GET] /shop/bookmark?sort={}&offset={}&limit={}  코드 리팩토링 + 버그 픽스
- 디폴트 sort 옵션 부여 (기존엔 sort 옵션 없으면 500에러 났음)
- 카테고리 데이터를 따로 불러와 붙이는 형식으로 수정 (limit개수만큼 불러오고 중복 카테고리를 정리했을 때 최종 결과로 출력되는 데이터 개수가 맞지 않는 버그 픽스)
- 저장된 소품샵이 없는 경우 404가 나오게 되어있었는데 200에 저장된 소품샵 없음 메시지가 뜨도록 수정 
- `npx mocha __test__/shop.spec.js`를 통해 테스트 실행 가능
- resolved: #94 (해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
<br/>
- 저장한 소품샵이 없는 경우를 테스트하기 위해 userId 5인 사람의 토큰을 발급받아 .env에 넣어두고 사용
=> [Test] 저장한 소품샵 불러오기 api 테스트코드 작성, 리팩토링

__test__/shop.spec.js, src/db/review.js, src/routes/review/index.js, src/routes/review/reviewShopIdSortOffsetLimitGET.js
<br/>
- 테스트 코드 작성
- 파라미터 검증 추가
- sort에 따라  DB에 요청 보내기 코드 개선
- resolved: #100 
<br/>
<br/>
=> [TEST] 해당 소품샵 관련 리뷰 목록 테스트 코드 작성, 리팩토링

__test__/shop.spec.js, src/routes/shop/shopShopIdLocationGET.js
<br/>
- 테스트 코드 작성
- shopId 검증 로직 추가
- resolved: #112 
<br/>
<br/>
=> [TEST] 소품샵 근처 지하철역 기반 소품샵 추천 테스트 코드 작성, 리팩토링

__test__/shop.spec.js, src/routes/shop/bookmarkPOST.js
<br/>
- 테스트 코드 작성
- 파라미터 검증 로직 강화
- resolved: #114 
<br/>
<br/>
=> [TEST] 소품샵 저장 테스트 코드 작성, 리팩토링

__test__/shop.spec.js, src/routes/review/reviewPOST.js
<br/>
- 테스트 코드 작성
- 파라미터 검증 강화
- resolved: #116 
<br/>
<br/>
=> [TEST] 리뷰 작성 테스트 코드 작성, 리팩토링

__test__/shop.spec.js, src/routes/shop/shopShopIdGET.js
<br/>
- shopId 검증 추가
- shopId 검증 테스트 코드 추가
- resolved: #98 
<br/>
<br/>
=> [TEST] 소품샵 상세페이지 코드리뷰 반영

__test__/shop.spec.js, src/db/shop.js, src/routes/shop/shopRecommendGET.js
<br/>
- [GET] /shop/recommend?type={} 테스트 코드 작성
- 작성 이후 테스트 통과 못한 내용 픽스(res값 중 필요없는 값도 전달되는 것들 정리) 
- resolved: #96(해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
<br/>
=> [TEST] 소품샵 추천 테스트 코드 작성, 리팩토링

__test__/shop.spec.js, src/constants/responseMessage.js, src/routes/shop/shopCategoryGET.js
<br/>
- /shop/category?type={} 테스트 코드 작성
- 쿼리 들어오는 부분 테스트
- 데이터 개수 맞는지 테스트
- /shop/category?type={} 리팩토링
- 주석 정리 
- 에러 처리 코드 추가
- 애매한 변수명 고치기
- resolved: #101 (해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
<br/>
=> [TEST] 카테고리별 소품샵 제공 테스트 코드 작성, 리팩토링

__test__/shop.spec.js, src/db/shop.js, src/routes/shop/shopSearchGET.js
<br/>
- /shop/search?keyword={} 테스트 코드 작성
- 비슷하게 작성했지만 프리뷰 이미지 배열의 길이가 1인지 체크하는 코드를 추가함, 다른 api에도 이 코드가 필요할 듯 하여 추가할 예정
- /shop/search?keyword={} 리팩토링
- 이미지 붙이는 과정이 구현되어있지 않아 이를 추가함
- 카테고리를 배열로 만드는 과정의 순서가 잘못되어 있어 이를 수정함
- resolved: #103 (해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
해당 api는 뷰가 아직 나오지않아 정확한 구현은 아님
나오고 나서 수정이 더 이루어져야 함 
특히 page나 offset과 같은 상황이 추가될 경우 코드 추가가 필요함
<br/>
=> [TEST] 소품샵 검색 기능 테스트 코드 작성, 리팩토링

__test__/review.spec.js, src/constants/responseMessage.js, src/routes/my/myReviewGET.js
<br/>
- /my/review/write 테스트코드 작성
- 리뷰 데이터를 가진 유저가 로그인한 경우, 반환 데이터 체크 
- 리뷰 데이터가 없는 유저가 로그인한 경우 테스트(다른 유저 토큰 이용해서)
- 로그인 안 되어 있을 때 접근 제어 테스트
- /my/review/write 리팩토링
- 리뷰 데이터 있는 경우와 없는 경우를 체크하는 에러 처리 부분에 .length 가 빠져있어서 이를 추가함
- 반환 데이터 이름을 좀 더 정확하게 수정함 
- resolved: #106 (해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
- 리뷰 데이터 있는 유저와 리뷰 데이터 없는 유저 토큰을 구별해서 사용하고 있음 -> env 파일에 두가지 유저를 저장해서 사용함(돌려볼때 잘 안돌아가면 아마 그 이유일 수 있으니 주의 바람)
- page나 offset 경우도 고민해야 할 듯, 현재는 리뷰 데이터가 적어 따로 얼마의 데이터를 제공할지 추가하지 않았지만 이후에는 추가해야할 것 같음
<br/>
=> [TEST] 내가 작성한 리뷰 가져오기 기능 테스트 코드 작성, 리팩토링

__test__/shop.spec.js, src/constants/responseMessage.js, src/db/review.js, src/routes/review/reviewRecentGET.js
<br/>
- /review/recent 테스트코드 작성
- /review/recent 리팩토링 
- resolved: #105 (해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
<br/>
=> [TEST] 최근 작성된 리뷰 보여주기 기능 테스트 코드 작성, 리팩토링

__test__/review.spec.js, src/constants/responseMessage.js
<br/>
- /my/review/scrap 테스트 코드 작성
- 스크랩한 리뷰 데이터를 가진 유저가 로그인한 경우, 반환 데이터 및 데이터 길이 체크
- 스크랩한 리뷰 데이터 없는 유저가 로그인한 경우 테스트(다른 유저 토큰 이용)
- 로그인 안 되어 있을 때 접근 제어 테스트
- /my/review/scrap 리팩토링
- 누락된 responseMessage 추가
- resolved: #109 (해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
- 리뷰 데이터 있는 유저와 리뷰 데이터 없는 유저 토큰을 구별해서 사용하고 있음 -> env 파일에 두가지 유저를 저장해서 사용함(돌려볼때 잘 안돌아가면 아마 그 이유일 수 있으니 주의 바람)
- page나 offset 경우도 고민해야 할 듯, 현재는 리뷰 데이터가 적어 따로 얼마의 데이터를 제공할지 추가하지 않았지만 이후에는 추가해야할 것 같음
<br/>
=> [TEST] 내가 스크랩한 리뷰 가져오기 기능 테스트 코드 작성, 리팩토링

src/constants/uploadPath.js, src/middlewares/uploadImage.js, src/routes/review/index.js
- uploadImage 파라미터로 경로 입력
- 경로는 constants/uploadPath에 작성
<br/>
- uploadImage 파라미터로 경로 입력
- 경로는 constants/uploadPath에 작성
- resolved: #131
<br/>
imageUpload 미들웨어 사용할 때 꼭 저장경로 써야합니다
저장경로는 constats/uploadPath에 설정해두었습니다
<br/>
=> ✨ [FEAT] : 이미지 업로드 경로 설정 기능 #131

src/constants/responseMessage.js, src/db/user.js, src/routes/auth/signup/index.js, src/routes/auth/signup/signupNicknamePOST.js, src/routes/auth/signup/signupPOST.js
<br/>
- 닉네임 중복 체크
- resolved: #127 #128 
<br/>
auth/authSignupPOST.js를 auth/signup 으로 이동시키고, 파일명 signupPOST.js로 변경
<br/>
=> [FEATURE] signup nickname #127

__test__/user.spec.js, src/routes/user/index.js, src/routes/user/userInfoGET.js
<br/>
- 회원 정보 가져오기
- 마이페이지에서 유저 정보 조회
- resolved: #140 
<br/>
<br/>
=> Feature/get user info #140

__test__/user.spec.js, src/routes/user/index.js, src/routes/user/userImageGET.js
<br/>
- 프로필 사진 가져오기
-
- resolved: #139 
<br/>
<br/>
=> Feature/get user image #139

__test__/user.spec.js, src/db/user.js, src/routes/user/index.js, src/routes/user/userThemeGET.js
<br/>
- 선호 소품 테마 가져오기
- resolved: #138 
<br/>
<br/>
=> Feature/get user theme #138

__test__/user.spec.js, src/constants/responseMessage.js, src/db/user.js, src/routes/user/index.js, src/routes/user/userImageDELETE.js
<br/>
- 현재 프로필 사진 삭제
- resolved: #137 
<br/>
<br/>
=> Feature/delete user image #137

src/db/index.js, src/db/theme.js, src/db/user.js, src/routes/user/index.js, src/routes/user/userThemePUT.js
<br/>
- 선호 소품 테마 수정
- resolved: #136 
<br/>
<br/>
=> ✨ [FEAT] : 선호 소품 테마 수정 #136

src/constants/uploadPath.js, src/db/user.js, src/middlewares/uploadImage.js, src/routes/user/index.js, src/routes/user/userImagePUT.js
<br/>
- 새로운 프로필 사진 등록
- resolved: #135 
<br/>
<br/>
=> Put user image #135

src/constants/responseMessage.js, src/db/user.js, src/routes/user/index.js, src/routes/user/userNicknamePUT.js
<br/>
- 닉네임 수정
- resolved: #134 
<br/>
<br/>
=> ✨ [FEAT] : 닉네임 수정 #134

src/routes/auth/signup/signupSendmailPOST.js
<br/>
- 이메일 인증번호 부분에서 이미 가입된 이메일을 요청했을때 명세에는 status:200, uniqueEmail : false, “verificationCode”: “” 로 보내준다고 했는데 실제로는 status:400으로 에러로 옴
-상태코드 200으로 변경
- resolved: #151 
<br/>
<br/>
=> 🔨 [FIX] : 이메일 인증번호 statusCode 수정 #151

src/routes/auth/signup/signupSendmailPOST.js
<br/>
- 이메일 인증번호 response 에서 statusCode 수정
-
- resolved: #151 
<br/>
<br/>
=> [FIX] 이메일 인증번호 response 수정 배포

src/routes/auth/signup/signupSendmailPOST.js
<br/>
- 인증번호 발송하는 이메일 내용 수정
-
- resolved: #154 
<br/>
<br/>
=> Fix/email content #154

src/constants/responseMessage.js, src/routes/my/myReviewGET.js
<br/>
- 이걸 했어
- 저것도 했어
-
- resolved: #156 
<br/>
<br/>
=> 🔨 [FIX] : 내가 작성한 리뷰 보기 어세스토큰 없을때 오류 수정 #156

src/db/adminUser.js, src/db/index.js, src/lib/jwtHandlers.js, src/middlewares/adminAuth.js, src/routes/admin/adminLoginPost.js, src/routes/admin/allReviewGET.js, src/routes/admin/allShopGET.js, src/routes/admin/index.js, src/routes/admin/shopDataGET.js
<br/>
- 어드민 인증 받아야만 어드민 api접근 가능하도록 로직 수정
- 어드민용 로그인 구현
- 기타 GET 제대로 오지 않는 부분 수정
- resolved: #159 #165 
<br/>
<br/>
=> Feat/admin get 어드민용 인가체계 구축

src/routes/auth/authLoginPOST.js
<br/>
- 로그인 api response에 닉네임 추가
- resolved: #167 (해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
간단한 내용입니다만 확인차 올립니다!
<br/>
=> [fix] 로그인 api response에 닉네임 추가 #167

src/constants/responseMessage.js, src/db/user.js, src/routes/auth/signup/signupPOST.js
<br/>
- 회원가입 시 테마 저장 로직 수정
- userThemePUT 로직 활용
- resolved: #169 
<br/>
<br/>
=> [Fix] 회원가입 테마 저장 수정 (fix/post-signup) #169

src/db/user.js, src/lib/jwtHandlers.js, src/routes/auth/authLoginPOST.js, src/routes/auth/signup/signupPOST.js
<br/>
- payload에 패스워드 대신 닉네임 담기도록 수정
- resolved: #172 (
<br/>
<br/>
=> fix: payload 수정

src/middlewares/uploadImage.js
<br/>
- s3, rds 새로운 계정으로 옮겼습니다
- resolved: #171 
<br/>
s3 더미데이터는 아직 예전 계정에 있어요. 
<br/>
=> [CHORE] : S3 버킷 이름 세팅 변경 #171

src/db/spreadsheet.js, src/dbscript/insertShopImage.js
이미지 없는 소품샵 리스트_이미지 url
안 열리는 이미지 안 넣음
<br/>
- 소품샵 이미지 DB에 넣기
- 안 열리는 이미지는 안 넣음 
- resolved: #174 
<br/>
<br/>
=> ✅ [CHORE] : 소품샵 이미지 DB에 넣기 #174

src/db/spreadsheet.js, src/dbscript/insertShopImage.js, src/middlewares/uploadImage.js
<br/>
- rds 새로 세팅
- s3 새로 세팅
- 소품샵 이미지 데이터 저장 (안 열리는 이미지 제외)
- resolved: #171 #174
<br/>
.env 파일 변경 있음
<br/>
=> rds, s3 세팅 및 소품샵 이미지 데이터 저장

src/app.js
<br/>
- 이걸 했어
- 저것도 했어
-
<br/>
<br/>
=> 🚑️ [HOTFIX] : cors 오류 수정

src/app.js
<br/>
- 이걸 했어
- 저것도 했어
-
<br/>
<br/>
=> hotfix: cors 오류

src/app.js
<br/>
- 이걸 했어
- 저것도 했어
-
<br/>
<br/>
=> 🚑️ [HOTFIX] : cors origin 헤더 추가

src/app.js
<br/>
- 이걸 했어
- 저것도 했어
-
<br/>
<br/>
=> 🚑️ [HOTFIX] : cors origin 여러 개 추가

src/app.js
<br/>
- 웹 배포시 발생하는 cors 에러 해결
- 여러가지 url에서도 모두 작동하게끔 수정
<br/>
- url 추가시 allowedOrigins 배열에 추가해주면 됩니다
<br/>
=> 🚑️ [HOTFIX] : cors origin multiple url 작동 코드

src/db/user.js
<br/>
- insert 쿼리 수정
- resolved: #188 
<br/>
<br/>
=> [FIX] 회원가입 안 되는 오류 수정 fix/signup #188

src/app.js
<br/>
- 회원가입 오류 수정
- resolved: #188 
<br/>
<br/>
=> [fix] 회원가입 오류 수정

src/db/review.js
<br/>
- 리뷰 필터 쿼리 수정
- resolved: #192
<br/>
<br/>
=> 🔨 [FIX] : 소품샵 상세, 리뷰 상세 리뷰 정렬 오류 수정 #192

package-lock.json, src/constants/responseMessage.js, src/db/review.js, src/routes/admin/adminReviewDelete.js, src/routes/admin/index.js, yarn.lock
<br/>
- 리뷰 삭제 기능 개발
- resolved: #179 
<br/>
<br/>
=> feat: Review 삭제 기능 개발

src/constants/responseMessage.js, src/db/shop.js, src/routes/admin/adminShopDELETE.js, src/routes/admin/index.js
<br/>
- 어드민 페이지 내에서 소품샵 삭제 기능 추가
- shopId params로 받아서 사용
- resolved: #199 
<br/>
<br/>
=> [feat] 어드민 소품샵 삭제 기능 추가 #199

src/constants/responseMessage.js, src/constants/uploadPath.js, src/db/category.js, src/db/index.js, src/db/review.js, src/db/shop.js, src/middlewares/adminAuth.js, src/routes/admin/existShopDataPUT.js, src/routes/admin/index.js, src/routes/admin/newShopDataPOST.js
<br/>
- /admin/shop/existshop api 개발 
- 기존 소품샵 이름을 받아서 소품샵 데이터 수정 가능
- 모든 데이터 다시 작성해줘야 하는 문제 있음
- 이는 앞으로 수정 예정.. 
- /admin/shop/newshop api 개발
- 새로운 소품샵 데이터 받아서 추가 가능  
- 중복인지 검사해주는 기능 아직 없음 수정 예정..
- 두 api 모두 formdata 통해서만 이미지 추가 가능
- resolved: #175(해당 Issue Number) 무슨 이슈에 대한 작업인지 명시합니다. 해당 이슈를 이곳에 적으면 pr merge 이후 해당 이슈는 자동으로 close 됩니다.
<br/>
- 수정할 부분이 아직 많고 api 명세서 그대로 코드 작성은 안 이루어짐.. 
- api 명세서 update 할 예정
- 이미지 추가시 무조건 formdata 통해서 update
- 이미지 preview 조건은 무조건 배열 첫 번째일 때 프리뷰가 됨
<br/>
=> [feat] 어드민 소품샵 데이터 추가 및 수정 기능 추가 #175

src/db/shop.js, src/routes/shop/shopRecommendGET.js
<br/>
- 소품샵 추천시 없는 소품샵 아이디는 안나오게끔 수정
- resolved: #202  
<br/>
<br/>
=> [fix] 소품샵 추천시 삭제된 소품샵 안나오게끔 수정 #202

src/db/spreadsheet.js, src/dbscript/insertReviewData.js, src/dbscript/insertShop.js, src/dbscript/insertShopImage.js, src/dbscript/insertUser.js
<br/>
- 스프레드시트에 있는 데이터를 DB에 추가하는 로직 다듬기
- resolved: #201
<br/>
이미지 넣을 때는 주석 잘 보고 해주세요
<br/>
=> Fix/db script #201
